### ISSUE TITLE
Frosty double jump

### ISSUE THREAD

**Issue by ArturKnaus** [Rudi75/Frostie#1]
If i press space and/or up key raptly, frosty sometimes jumps twice, even if he isn't grounded 

Edit:
When he's grounded, double tap jump -> double jump

**Comment by Rudi75** [comment]
Complete frostie or parts?

**Comment by ArturKnaus** [comment]
complete frosty as it is in the master branch (scene 0)

**Comment by ArturKnaus** [comment]
Demo of bug
https://www.youtube.com/watch?v=FOKBAGtNtFU
